/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u0_a255
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuFuncionario = new javax.swing.JMenu();
        menuItemMonitorarFunc = new javax.swing.JMenuItem();
        menuItemVendas = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        menuItemMonitorarProd = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/java-logo_1.png")).getImage()
        );

        jMenuBar1.setToolTipText("");

        menuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        menuFuncionario.setText("Funcionários");
        menuFuncionario.setToolTipText("");

        menuItemMonitorarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        menuItemMonitorarFunc.setText("Monitorar");
        menuItemMonitorarFunc.addActionListener(this::menuItemMonitorarFuncActionPerformed);
        menuFuncionario.add(menuItemMonitorarFunc);

        menuItemVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        menuItemVendas.setText("Vendas");
        menuItemVendas.addActionListener(this::menuItemVendasActionPerformed);
        menuFuncionario.add(menuItemVendas);

        jMenuBar1.add(menuFuncionario);

        menuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/package.png"))); // NOI18N
        menuProduto.setText("Produtos");

        menuItemMonitorarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoom.png"))); // NOI18N
        menuItemMonitorarProd.setText("Monitorar");
        menuItemMonitorarProd.addActionListener(this::menuItemMonitorarProdActionPerformed);
        menuProduto.add(menuItemMonitorarProd);

        jMenuBar1.add(menuProduto);

        menuInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        menuInfo.setText("Info");

        menuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/door.png"))); // NOI18N
        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(this::menuItemSairActionPerformed);
        menuInfo.add(menuItemSair);

        jMenuBar1.add(menuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemMonitorarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMonitorarFuncActionPerformed
        
        new FuncionarioJTable().setVisible(true);
    }//GEN-LAST:event_menuItemMonitorarFuncActionPerformed

    private void menuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendasActionPerformed

        new VendaJTable().setVisible(true);
    }//GEN-LAST:event_menuItemVendasActionPerformed

    private void menuItemMonitorarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMonitorarProdActionPerformed

        new ProdutoJTable().setVisible(true);
    }//GEN-LAST:event_menuItemMonitorarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenuItem menuItemMonitorarFunc;
    private javax.swing.JMenuItem menuItemMonitorarProd;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemVendas;
    private javax.swing.JMenu menuProduto;
    // End of variables declaration//GEN-END:variables
}
